#!/bin/bash
# Regenerate frontend/.env.local and backend/.env from the root .env file.
# Usage: bash sync_env.sh
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_ENV="$SCRIPT_DIR/.env"

if [[ ! -f "$ROOT_ENV" ]]; then
  echo "Error: $ROOT_ENV not found." >&2
  exit 1
fi

# Load root .env
set -a
# shellcheck disable=SC1090
source "$ROOT_ENV"
set +a

# ── frontend/.env.local ───────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/frontend/.env.local" <<EOF
# Auto-generated by sync_env.sh — edit root .env instead.
NEXT_PUBLIC_USE_MOCK=false
NEXT_PUBLIC_API_BASE=${API_NGROK_URL}
NEXT_PUBLIC_CV_BASE=${CV_NGROK_URL}
NEXT_PUBLIC_CV_LOCAL=${CV_LOCAL_URL}
CV_BASE_INTERNAL=${CV_LOCAL_URL}
EOF
echo "✓ frontend/.env.local"

# ── backend/.env ──────────────────────────────────────────────────────────────
cat > "$SCRIPT_DIR/backend/.env" <<EOF
# Auto-generated by sync_env.sh — edit root .env instead.
ARES_DB_URL=${ARES_DB_URL}
ARES_TEST_DB_URL=${ARES_TEST_DB_URL}
SECRET_KEY=${SECRET_KEY}
ACCESS_TOKEN_TTL=${ACCESS_TOKEN_TTL}
GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
FRONTEND_URL=${FRONTEND_URL}
CV_API_BASE=${CV_NGROK_URL}
CV_INTERNAL_BASE=${CV_LOCAL_URL}
ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
NVIDIA_API_KEY=${NVIDIA_API_KEY}
EOF
echo "✓ backend/.env"

echo ""
echo "Done. Restart your services to pick up the changes."
